require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MikeHudickSamplesController do

  # This should return the minimal set of attributes required to create a valid
  # MikeHudickSample. As you add validations to MikeHudickSample, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MikeHudickSamplesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mike_hudick_samples as @mike_hudick_samples" do
      mike_hudick_sample = MikeHudickSample.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mike_hudick_samples).should eq([mike_hudick_sample])
    end
  end

  describe "GET show" do
    it "assigns the requested mike_hudick_sample as @mike_hudick_sample" do
      mike_hudick_sample = MikeHudickSample.create! valid_attributes
      get :show, {:id => mike_hudick_sample.to_param}, valid_session
      assigns(:mike_hudick_sample).should eq(mike_hudick_sample)
    end
  end

  describe "GET new" do
    it "assigns a new mike_hudick_sample as @mike_hudick_sample" do
      get :new, {}, valid_session
      assigns(:mike_hudick_sample).should be_a_new(MikeHudickSample)
    end
  end

  describe "GET edit" do
    it "assigns the requested mike_hudick_sample as @mike_hudick_sample" do
      mike_hudick_sample = MikeHudickSample.create! valid_attributes
      get :edit, {:id => mike_hudick_sample.to_param}, valid_session
      assigns(:mike_hudick_sample).should eq(mike_hudick_sample)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MikeHudickSample" do
        expect {
          post :create, {:mike_hudick_sample => valid_attributes}, valid_session
        }.to change(MikeHudickSample, :count).by(1)
      end

      it "assigns a newly created mike_hudick_sample as @mike_hudick_sample" do
        post :create, {:mike_hudick_sample => valid_attributes}, valid_session
        assigns(:mike_hudick_sample).should be_a(MikeHudickSample)
        assigns(:mike_hudick_sample).should be_persisted
      end

      it "redirects to the created mike_hudick_sample" do
        post :create, {:mike_hudick_sample => valid_attributes}, valid_session
        response.should redirect_to(MikeHudickSample.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mike_hudick_sample as @mike_hudick_sample" do
        # Trigger the behavior that occurs when invalid params are submitted
        MikeHudickSample.any_instance.stub(:save).and_return(false)
        post :create, {:mike_hudick_sample => { "name" => "invalid value" }}, valid_session
        assigns(:mike_hudick_sample).should be_a_new(MikeHudickSample)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MikeHudickSample.any_instance.stub(:save).and_return(false)
        post :create, {:mike_hudick_sample => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mike_hudick_sample" do
        mike_hudick_sample = MikeHudickSample.create! valid_attributes
        # Assuming there are no other mike_hudick_samples in the database, this
        # specifies that the MikeHudickSample created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MikeHudickSample.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => mike_hudick_sample.to_param, :mike_hudick_sample => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested mike_hudick_sample as @mike_hudick_sample" do
        mike_hudick_sample = MikeHudickSample.create! valid_attributes
        put :update, {:id => mike_hudick_sample.to_param, :mike_hudick_sample => valid_attributes}, valid_session
        assigns(:mike_hudick_sample).should eq(mike_hudick_sample)
      end

      it "redirects to the mike_hudick_sample" do
        mike_hudick_sample = MikeHudickSample.create! valid_attributes
        put :update, {:id => mike_hudick_sample.to_param, :mike_hudick_sample => valid_attributes}, valid_session
        response.should redirect_to(mike_hudick_sample)
      end
    end

    describe "with invalid params" do
      it "assigns the mike_hudick_sample as @mike_hudick_sample" do
        mike_hudick_sample = MikeHudickSample.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MikeHudickSample.any_instance.stub(:save).and_return(false)
        put :update, {:id => mike_hudick_sample.to_param, :mike_hudick_sample => { "name" => "invalid value" }}, valid_session
        assigns(:mike_hudick_sample).should eq(mike_hudick_sample)
      end

      it "re-renders the 'edit' template" do
        mike_hudick_sample = MikeHudickSample.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MikeHudickSample.any_instance.stub(:save).and_return(false)
        put :update, {:id => mike_hudick_sample.to_param, :mike_hudick_sample => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mike_hudick_sample" do
      mike_hudick_sample = MikeHudickSample.create! valid_attributes
      expect {
        delete :destroy, {:id => mike_hudick_sample.to_param}, valid_session
      }.to change(MikeHudickSample, :count).by(-1)
    end

    it "redirects to the mike_hudick_samples list" do
      mike_hudick_sample = MikeHudickSample.create! valid_attributes
      delete :destroy, {:id => mike_hudick_sample.to_param}, valid_session
      response.should redirect_to(mike_hudick_samples_url)
    end
  end

end
